VERSION="2.2.1"

ACCOUNTS=["GB6AWOG77K5MMUTTT6THE4DLQX54JU7BAHOO7FO3BE6DJUZJ4FZSDZAX"]

[DOCUMENTATION]
ORG_NAME="Newcrest Mining"
ORG_URL="https://www.stellarnewcrest.com/"
ORG_DESCRIPTION="Newcrest Mining Limited is an Australian-based corporation which engages in the exploration, development, mining and sale of gold and the froth flotation product, gold-copper concentrate."
ORG_LOGO="https://www.stellarnewcrest.com/new.png"


[[CURRENCIES]]
code="NGOLD"
status="live"
display_decimals=2
issuer="GB6AWOG77K5MMUTTT6THE4DLQX54JU7BAHOO7FO3BE6DJUZJ4FZSDZAX"
anchor_asset_type="crypto"
name="GOLD"
desc="Newcrest Mining Limited is an Australian-based corporation which engages in the exploration, development, mining and sale of gold and the froth flotation product, gold-copper concentrate."
image="https://www.stellarnewcrest.com/new.png"
